# Generated by Django 4.1.7 on 2023-03-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Other', help_text='Enter the name of the bank (e.g. SEB)', max_length=100, verbose_name='Bank name')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Account balance')),
                ('investment', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Investment balance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(blank=True, default='Other', help_text='Enter the company or seller (e.g. "Maxima")', max_length=100, verbose_name='Company or seller')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Company or seller',
                'verbose_name_plural': 'Companies and sellers',
            },
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='Other', help_text='Enter the source of the income (e.g. university)', max_length=100, verbose_name='Source of income')),
                ('earner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Source of income',
                'verbose_name_plural': 'Sources of income',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, default='Other', help_text='Enter the category of the income (e.g. salary)', max_length=100, verbose_name='Category definition')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Income category',
                'verbose_name_plural': 'Income categories',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of data input')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of receipt')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Amount of income')),
                ('notes', models.TextField(blank=True, default='There are no additional notes', max_length=2000, verbose_name='Client notes')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='income_pdfs', verbose_name='PDF document')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bank', verbose_name='Income bank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.incomecategory', verbose_name='Income category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.incomesource', verbose_name='Income source')),
            ],
            options={
                'verbose_name': 'Income line',
                'verbose_name_plural': 'Income lines',
            },
        ),
        migrations.CreateModel(
            name='ExpensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, default='Other', help_text='Enter the category of the expenses (e.g. groceries)', max_length=100, verbose_name='Category definition')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Expenses category',
                'verbose_name_plural': 'Expenses categories',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of data input')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of receipt')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Amount of expenses')),
                ('notes', models.TextField(blank=True, default='There are no additional notes', max_length=2000, verbose_name='Client notes')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='expenses_pdfs', verbose_name='PDF document')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.bank', verbose_name='Expenses bank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.expensescategory', verbose_name='Expenses category')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.seller', verbose_name='Company or seller')),
            ],
            options={
                'verbose_name': 'Line expenses',
                'verbose_name_plural': 'Lines expenses',
            },
        ),
    ]
