# Generated by Django 4.1.7 on 2023-03-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_bank_seller_incomesource_incomecategory_income_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Line of expenses', 'verbose_name_plural': 'Lines of expenses'},
        ),
    ]
