# Generated by Django 4.1.7 on 2023-03-30 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name': 'Line of expenses', 'verbose_name_plural': 'Lines of expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensescategory',
            options={'ordering': ['definition'], 'verbose_name': 'Expenses category', 'verbose_name_plural': 'Expenses categories'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income line', 'verbose_name_plural': 'Income lines'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ['definition'], 'verbose_name': 'Income category', 'verbose_name_plural': 'Income categories'},
        ),
        migrations.AlterModelOptions(
            name='incomesource',
            options={'ordering': ['source'], 'verbose_name': 'Source of income', 'verbose_name_plural': 'Sources of income'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['seller'], 'verbose_name': 'Company or seller', 'verbose_name_plural': 'Companies and sellers'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
