# Generated by Django 4.1.7 on 2023-03-30 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_alter_bank_options_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
